[build]
  command = "pip install -r requirements.txt"
  publish = "app/static"
  functions = "netlify/functions"

[dev]
  framework = "flask"
  command = "flask run"
  port = 5000
  targetPort = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
